[package]
name = "fuzz_suite"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
plotters = "0.3"
thiserror = "1.0"
walkdir = "2"
tempfile = "3.15.0"

[dev-dependencies]
criterion = "0.5"

[features]
default = []
coverage = [] # Enable LLVM coverage instrumentation
